services:
  caddy:
    image: docker.io/caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
  drasl:
    image: docker.io/unmojang/drasl
    volumes:
      - ./config:/etc/drasl
      - ./data:/var/lib/drasl
