# Drasl default config file

# Example: drasl.example.com
Domain = "CHANGEME"

# Example: https://drasl.example.com
BaseURL = "https://CHANGEME"

# List of usernames who automatically become admins of the Drasl instance
DefaultAdmins = [""]

[CreateNewPlayer]
AllowChoosingUUID = true

[RegistrationNewPlayer]
Allow = true
RequireInvite = true
